- stat: path=/root/docker/dockerhub-webhook/.env
  register: token_file

- name: copy docker compose files
  copy: src="{{ role_path }}/files/{{item}}" dest="/root/docker"
  register: docker_compose_projects
  with_items:
    - "dockerhub-webhook"
  notify:
    - restart docker compose

- name: add executable mode to deploy script
  file:
    path: "/root/docker/dockerhub-webhook/scripts/deploy-compose"
    mode: "0755"

- name: add executable mode to deploy script wrapper
  file:
    path: "/root/docker/dockerhub-webhook/scripts/deploy-compose-if-newer"
    mode: "0755"

- name: copy deploy script
  file:
    state: link
    force: "yes"
    src: "/root/docker/dockerhub-webhook/scripts/deploy-compose"
    dest: "/usr/local/bin/deploy-compose"

- name: create dockerhub-webhook config
  template:
    src: "{{ role_path }}/templates/dockerhub-webhook/scripts/index.js.j2"
    dest: /root/docker/dockerhub-webhook/scripts/index.js

- name: generate token
  shell: echo "TOKEN="`uuidgen` > /root/docker/dockerhub-webhook/.env
  when: token_file.stat.exists == False
  notify:
    - restart docker compose
