---
# - name: Creates docker compose directory
#   file: path=/root/{{docker_deployment}} state=directory

- name: copy docker compose file
  copy: src="{{ role_path }}/files/{{docker_deployment}}" dest="/root"
  notify:
    - restart docker compose
