---
- name: Creates docker compose directory
  file: path=/root/{{docker_deployment}} state=directory

- name: copy docker compose file
  template: src=files/{{docker_deployment}} dest=/root/
  notify:
    - restart docker compose
