---
version: '3'
services:
  openldap:
    restart: "always"
    image: osixia/openldap:1.2.4
    command: "--copy-service"
    ports:
      - 3389:389
      - 6366:636
    environment:
      LDAP_ORGANISATION: OpenMRS
      LDAP_DOMAIN: ${LDAP_DOMAIN:-openmrs.org}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-admin}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD:-config}
      LDAP_TLS_CRT_FILENAME: ${LDAP_TLS_CRT_FILENAME:-ldap.crt}
      LDAP_TLS_KEY_FILENAME: ${LDAP_TLS_KEY_FILENAME:-ldap.key}
      LDAP_TLS_CA_CRT_FILENAME: ${LDAP_TLS_CA_CRT_FILENAME:-ca.crt}
      LDAP_TLS_VERIFY_CLIENT: never
      LDAP_LOG_LEVEL: 0
    healthcheck:
      test: "exit 0"
    volumes:
      - config-ldap:/etc/ldap/slapd.d
      - database-ldap:/var/lib/ldap
      - ./bootstrap:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ${CERTS_DIR-./certs}:/container/service/slapd/assets/certs/

  ldap:
    restart: "always"
    image: osixia/openldap:1.1.8
    ports:
      - 636:636
    environment:
      LDAP_ORGANIZATION: OpenMRS
      LDAP_DOMAIN: ${OLD_LDAP_DOMAIN:-openmrs.org}
      LDAP_ADMIN_PASSWORD: ${OLD_LDAP_ADMIN_PASSWORD:-admin}
      LDAP_TLS_CRT_FILENAME: ${OLD_LDAP_TLS_CRT_FILENAME:-ldap.crt}
      LDAP_TLS_KEY_FILENAME: ${OLD_LDAP_TLS_KEY_FILENAME:-ldap.key}
      LDAP_TLS_CA_CRT_FILENAME: ${OLD_LDAP_TLS_CA_CRT_FILENAME:-ca.crt}
      LDAP_TLS_VERIFY_CLIENT: never
      LDAP_LOG_LEVEL: 0
    healthcheck:
      test: "exit 0"
    volumes:
      - config:/etc/ldap/slapd.d
      - database:/var/lib/ldap
      - ${OLD_CERTS_DIR-./certs_old}:/container/service/slapd/assets/certs/

volumes:
  config:
  database:
  config-ldap:
  database-ldap:
