version: '2.1'

services:
  app:
    image: burke/quizgrader:latest
    env_file:
     - .env
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      timeout: 20s
