---
version: '3'
services:
  ldap:
    image: osixia/openldap:1.1.10
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_ORGANIZATION: OpenMRS
      LDAP_DOMAIN: ${LDAP_DOMAIN:-openmrs.org}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-admin}

    volumes:
      - config:/etc/ldap/slapd.d
      - database:/var/lib/ldap
volumes:
  config:
  database:
